.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH zola-check 1  "check " 
.SH NAME
zola\-check \- Try to build the project without rendering it. Checks links
.SH SYNOPSIS
\fBzola check\fR [\fB\-\-drafts\fR] [\fB\-\-skip\-external\-links\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Try to build the project without rendering it. Checks links
.SH OPTIONS
.TP
\fB\-\-drafts\fR
Include drafts when loading the site
.TP
\fB\-\-skip\-external\-links\fR
Skip external links
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
