.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH zola-completion 1  "completion " 
.SH NAME
zola\-completion \- Generate shell completion
.SH SYNOPSIS
\fBzola completion\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR> 
.SH DESCRIPTION
Generate shell completion
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISHELL\fR>
Shell to generate completion for
.br

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh]
