.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH zola-init 1  "init " 
.SH NAME
zola\-init \- Create a new Zola project
.SH SYNOPSIS
\fBzola init\fR [\fB\-f\fR|\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
Create a new Zola project
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-force\fR
Force creation of project even if directory is non\-empty
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR] [default: .]
Name of the project. Will create a new directory with that name in the current directory
